### ISSUE TITLE
Wish: Translation for Chat-Message "Save"

### ISSUE THREAD

**Issue by Pasley70** [juho-jaakkola/elgg-chat#4]
Some users of my network reported to me that they wanted a more logical labeling of the "Save" button on the chat message page. Is it possible to add the label to the translation-array, like 'chat:message:save' => 'save', so we can translate it to 'send' or 'send message'?

**Comment by juho-jaakkola** [comment]
The word "Send" is available also in Elgg core: https://github.com/Elgg/Elgg/blob/1.10/languages/en.php#L818

But it might indeed be safer to add an own translation string to allow customized translations.

**Comment by Pasley70** [comment]
Yes - it might be confusing, if all save buttons of the network show 'send message' ;-)

**Comment by juho-jaakkola** [comment]
Done

**Comment by Pasley70** [comment]
Many thanx!

**Comment by Pasley70** [comment]
Her a German translation, if you my want to add.

<pre>
/**
 * Chat German language file.
 */

$german = array(
	'chat' => 'Chat',
	'chat:chats' => 'Chats',
	'chat:view:all' => 'Zeige alle chats',
	'chat:chat' => 'Chat',
	'item:object:chat' => 'Chat',
	'item:object:chat_message' => 'Chat-Nachricht',
	'chat:none' => 'Keine Chats',
	'chat:more' => 'Zeige mehr',

	'chat:title:user_chats' => '%s\'s Chats',
	'chat:title:all_chats' => 'Alle Seiten-Chats',
	'chat:title:friends' => 'Freunde Chats',
	'chat:messages' => 'Chat-Nachrichten',
	'chat:members' => 'Teilnehmer hinzufügen',
	'chat:members:add' => 'Teilnehmer hinzufügen',
	'chat:leave' => 'Verlassen',
	'chat:leave:confirm' => 'Bist Du sicher, dass Du diesen Chat dauerhaft verlassen willst? Nach dem Verlassen kannst Du an diesem Chat nicht mehr teilnehmen.',
	'chat:members:more' => "+%s andere",
	'chat:unread_message' => '%s ungelesen',
	'chat:unread_messages' => '%s ungelesen', // Plurar

	'chat:group' => 'Gruppen Chat',
	'chat:enablechat' => 'Ermögliche Gruppen Chat',
	'chat:write' => 'Starte einen Chat',
	'chat:message:send' => 'Senden',

	// Editing
	'chat:add' => 'Starte einen Chat',
	'chat:edit' => 'Bearbeite Chat',
	'chat:members:manage' => 'Teilnehmer hinzufügen/löschen',
	'chat:delete:confirm' => 'Willst Du wirklich diesen Chat und alle Nachrichten darin entfernen?',
	'chat:title' => 'Chat Titel',
	'chat:message' => 'Nachricht',

	// messages
	'chat:message:saved' => 'Chat gespeichert',
	'chat:message:deleted' => 'Chat gelöscht',
	'chat:message:chat_message:saved' => 'Nachricht gespeichert',
	'chat:message:chat_message:deleted' => 'Nachricht gelöscht',
	'chat:message:members:saved' => 'Teilnehmer hinzugefügt',
	'chat:message:members:saved:plurar' => '%s Teinehmer hinzugefügt',
	'chat:message:left' => 'Du hast den Chat verlassen.',
	'chat:error:cannot_save' => 'Chat kann nicht gestartet werden.',
	'chat:error:cannot_save_message' => 'Nachricht konnte nicht gespeichert werden.',
	'chat:error:cannot_write_to_container' => 'Unzureichender Zugang um eine Gruppen-Chat zu starten.',
	'chat:error:cannot_add_member' => 'Fehler beim Hinzufügen des Benutzers %s zum Chat.',
	'chat:error:cannot_delete' => 'Chat kann nicht gelöscht werden.',
	'chat:error:missing:title' => 'Bitte gebe einen Titel an!',
	'chat:error:missing:members' => 'Keine Teilnehmer ausgewählt!',
	'chat:error:cannot_edit_post' => 'Dieser Chat ist möglicherweise nicht vorhanden, oder Sie haben keine Berechtigung, diesen zu bearbeiten.',
	'chat:error:cannot_leave' => 'Fehler beim Verlassen des Chats',

	// river
	'river:create:object:chat' => '%s startete den Chat %s',

	// user settings
	'chat:usersettings:emailnotification' => 'Eine E-Mail-Benachrichtigung senden, wenn ich eine neue Nachricht erhalte.',

	// notifications
	'chat:notification:subject:newpost' => 'Eine neue Chatnachricht',
	'chat:notification:newpost' =>
'
%s schrieb eine neue Nachricht im Chat "%s".

Sie heißt:

"%s"

Nachrichten im Chat anzeigen und senden:
%s
',
	'chat:notification:subject:newchat' => 'Ein neuer Chat',
	'chat:notification:newchat' =>
'
%s hat dich zum Chat "%s" hinzugefügt.

Nachrichten im Chat anzeigen und senden:
%s
',

	// widget
	'chat:widget:description' => 'Deine aktuellen Chat-Nachrichten anzeigen',
	'chat:morechats' => 'Weitere Chats',
	'chat:numbertodisplay' => 'Anzahl der anzuzeigenden Chat-Nachrichten',
	'chat:nochats' => 'Keine Chat-Nachrichten'
);

add_translation('de', $german);
</pre>

**Comment by juho-jaakkola** [comment]
Thanks! I'll add it.
