### ISSUE TITLE
Chat notification

### ISSUE THREAD

**Issue by Pasley70** [juho-jaakkola/elgg-chat#6]
If i start a new Chat, i get a Notification "A new Chat" (without a Link). Maybe this Notification is not important for the creator of the Chat.

The members get a more specific notification (Creator of the Chat, Chat Title, Link to the Chat). Thats OK!

**Comment by juho-jaakkola** [comment]
Yeah, the creator is not supposed to receive a notification.

**Comment by Pasley70** [comment]
I've discovered that the site notification for RECIPIENTS is also not correct (the E-Mail-Notification is correct!). The recipients site notification - on opening a new chat - has no title and link to the chat, but just pointing "A new Chat" with a "broken" icon. It would be useful, if the recipient get the same information on the site as in the E-Mail. Maybe a conflict with new site notification in 1.9?

**Comment by juho-jaakkola** [comment]
I created a new issue for this: #7
